{"trial_id": "0001", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001], "ordered": true}}], "values": {"learning_rate": 0.01, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 4, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/shosamane/.local/lib/python3.10/site-packages/keras_tuner/engine/base_tuner.py\", line 250, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/shosamane/.local/lib/python3.10/site-packages/keras_tuner/engine/base_tuner.py\", line 215, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/shosamane/.local/lib/python3.10/site-packages/keras_tuner/tuners/hyperband.py\", line 401, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/shosamane/.local/lib/python3.10/site-packages/keras_tuner/engine/tuner.py\", line 284, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/home/shosamane/.local/lib/python3.10/site-packages/keras_tuner/engine/tuner.py\", line 211, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/home/shosamane/.local/lib/python3.10/site-packages/keras_tuner/engine/hypermodel.py\", line 142, in fit\n    return model.fit(*args, **kwargs)\n  File \"/home/shosamane/.local/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/shosamane/.local/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n    return fn(*args, **kwargs)\nTypeError: Model.fit() got an unexpected keyword argument 'callback'\n"}